version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_DATABASE_TYPE=sqlite3
      - GF_DATABASE_PATH=/var/lib/grafana/grafana.db
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - ./dashboards:/var/lib/grafana/dashboards
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./conf/defaults.ini:/usr/share/grafana/conf/defaults.ini
  speedtest:
    depends_on:
      - grafana
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speedtest
    volumes:
      - ./grafana:/var/lib/grafana
    command: /var/lib/grafana/grafana.db
    